# Generated by Django 4.2.3 on 2023-07-29 21:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 29, 21, 39, 40, 333069, tzinfo=datetime.timezone.utc)),
        ),
    ]
