# Generated by Django 4.2.3 on 2023-07-30 21:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_publish_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 30, 21, 44, 26, 178699, tzinfo=datetime.timezone.utc)),
        ),
    ]
