# Generated by Django 4.2.3 on 2023-07-31 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 31, 20, 49, 2, 271108, tzinfo=datetime.timezone.utc)),
        ),
    ]
